spring:
  datasource:
    url: jdbc:h2:mem:taskdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  flyway:
    enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
